// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Game struct {
	ID    int64
	White sql.NullInt64
	Black sql.NullInt64
}

type User struct {
	ID       int64
	Username string
	Password string
}
